### ISSUE TITLE
Make it more obvious eza is a rust project

### ISSUE THREAD

**Issue by ChromMob** [eza-community/eza.rocks#16]
Description:
The Eza website doesn't mention anywhere in the initial viewport that the project is written in Rust. This information is important to see right away, especially for visitors interested in Rust-based projects.

Suggestion:
Please consider adding a mention or badge for Rust in the initial viewport (e.g., near the header or tagline) to make the tech stack clear to new visitors. Thanks!

**Comment by cafkafk** [comment]
I mean it does mention it's on crates.io, but I suppose that may not make it obvious to some people. 

I do feel it's a delicate balance of being tasteful about mentioning it. The whole "blazing fast" thing can easily get quite tacky, but perhaps we should at least mention it more visibly.

**Comment by cafkafk** [comment]
Would this be sufficient? Added it to the text under the title

![2024-11-07_19-03](https://github.com/user-attachments/assets/81d1e90d-860e-4500-8848-375200ea3a3f)

**Comment by ChromMob** [comment]
That looks good.
