### ISSUE TITLE
bug: eza.rocks pre-processing/rendering error 

### ISSUE THREAD

**Issue by dimitrilw** [eza-community/eza.rocks#3]
Basically, the expanded sections are not rendered properly. See screenshot, below. It appears that the markdown-to-html conversion is not processing all content.

I was viewing the site via Chrome browser, Version 117.0.5938.132; current version as of the time of this post.

I do not believe that info is relevant, as it appears to be a pre-processing issue, not a browser issue. But deets matter. 😄

![image](https://github.com/eza-community/eza.rocks/assets/5898931/3049545d-e217-406d-b7f3-e86056e2225d)

**Comment by aarondill** [comment]
I've come across this same issue using safari on my iPhone, thusly confirming that platform/version doesn't matter

**Comment by Magniquick** [comment]
Can confirm on firefox nightly on Android.

**Comment by trk9001** [comment]
This was fixed in #8 I believe.

**Comment by dimitrilw** [comment]
Looks good in Firefox on MacOS.

<img width="617" alt="image" src="https://github.com/eza-community/eza.rocks/assets/5898931/6d4b166a-a0ec-4e82-86fa-0449801b809c">

Looks good in Safari on MacOS.

<img width="635" alt="image" src="https://github.com/eza-community/eza.rocks/assets/5898931/894b58bc-ec8c-4f78-a6b0-56db216b927c">

Also good in Safari on both iPad & iPhone.

Marking closed!
